apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops-task
type: Opaque
data:
  MONGO_ROOT_PASSWORD: YWRtaW4xMjMK
  MONGO_URI: bW9uZ29kYjovL21vbmdvdXNlcjphZG1pbjEyM0Btb25nbzoyNzAxNy90b2RvX2RiP2F1dGhTb3VyY2U9YWRtaW4K
  