version: '3.8'

services:
  app:
    image: docker.io/arafinahmed/devops-task:1.0  
    container_name: todo_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://arafin:admin123@mongo:27017/todo_db?authSource=admin
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:8.0.9-noble
    container_name: todo_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=arafin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=todo_db
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
