version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DB: todo_db
    depends_on:
      - mysql
    networks:
      - todo-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: todo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_INITDB_SKIP_TZINFO: 1
    command: --default-authentication-plugin=mysql_native_password --default-storage-engine=MyISAM
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
